const DC = [
    {
        id:1,
        vigilante:[
            {
                character:'Batman',
                bio:'',
                image:'',
            },
            {
                character:'NightWing',
                bio:'',
                image:'',
            },
            {
                character:'Red Robin',
                bio:'',
                image:'',
            },
            {
                character:'Red Hood',
                bio:'',
                image:'',
            },
            {
                character:'Batgirl',
                bio:'',
                image:'',
            },
            {
                character:'Robin',
                bio:'',
                image:'',
            },
            {
                character:'Alfred',
                bio:'',
                image:'',
            },
            {
                character:'Lucas Foc',
                bio:'',
                image:'',
            }
        ],
        villains:[
            {
                character:'Joker',
                bio:'',
                image:'',
            },
            {
                character:'Penguin',
                bio:'',
                image:'',
            },
            {
                character:'Two Face',
                bio:'',
                image:'',
            },
            {
                character:'Ras Al Ghul',
                bio:'',
                image:'',
            },
            {
                character:'Mr Freeze',
                bio:'',
                image:'',
            },
            {
                character:'Catwoman',
                bio:'',
                image:'',
            },
            {
                character:'Harley Quinn',
                bio:'',
                image:'',
            },
            {
                character:'The Riddler',
                bio:'',
                image:'',
            },
            {
                character:'Bane',
                bio:'',
                image:'',
            },
            {
                character:'Scarecrow',
                bio:'',
                image:'',
            },
            {
                character:'Deathstroke',
                bio:'',
                image:'',
            },
        ],
        movies:[
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            }
        ],
        television:[
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            }
        ],
        games:[
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            },
            {
                image:'',
                title:'',
                description:'',
            }
        ]
    }
]